In [17]:
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

# Embeddings & cosine similarity

In [3]:
model = SentenceTransformer("paraphrase-multilingual-MiniLM-L12-v2")

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

C:\Users\Student\AppData\Roaming\Python\Python312\site-packages\huggingface_hub\file_download.py:137: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Student\.cache\huggingface\hub\models--sentence-transformers--paraphrase-multilingual-MiniLM-L12-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/3.89k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/645 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/471M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/526 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.08M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [4]:
embeddings = model.encode("Кіт спить на дивані")

In [5]:
print(len(embeddings))

384


In [6]:
print(embeddings[:10])

[ 0.45195347 -0.33260477 -0.12180807  0.11641806  0.14532715  0.2734191
  0.03805364  0.18581052 -0.00748935 -0.04451016]


In [7]:
texts = [
    "Кіт спить на дивані",
    "На дивані спить кішка",
    "Сьогодні йде сильний дощ"
]

In [8]:
embeddings = model.encode(texts)

In [9]:
print(cosine_similarity(embeddings))

[[ 1.          0.98969674 -0.03308498]
 [ 0.98969674  1.0000001  -0.01803508]
 [-0.03308498 -0.01803508  1.        ]]


In [ ]:
# |       |      Кіт |    Кішка |      Дощ |
# | ----- | -------: | -------: | -------: |
# | Кіт   | **1.00** | **0.98** |     0.03 |
# | Кішка | **0.98** | **1.00** |     0.01 |
# | Дощ   |     0.03 |     0.01 | **1.00** |

# Semantic search

In [12]:
documents = [
    "The product quality is excellent and the design is modern.",
    "The delivery was late and the package was damaged.",
    "Customer support helped me reset my account password.",
    "The price is high but the product works well.",
    "The mobile app crashes during payment.",
]

queries = [
    "I need help with my password.",
    "The item arrived too late.",
    "The app has a payment bug.",
]
 

In [10]:
model = SentenceTransformer("all-MiniLM-L6-v2")

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

C:\Users\Student\AppData\Roaming\Python\Python312\site-packages\huggingface_hub\file_download.py:137: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Student\.cache\huggingface\hub\models--sentence-transformers--all-MiniLM-L6-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [22]:
doc_embeddings = model.encode(documents, normalize_embeddings=True)


for query in queries:
    print("Query: ", query)
    query_embeddings = model.encode([query], normalize_embeddings=True)
    
    print("query_embeddings.shape ", query_embeddings.shape)
    print("doc_embeddings.shape ", doc_embeddings.shape)
    print("doc_embeddings.T.shape ", doc_embeddings.T.shape) # Transpose
    
    scores = query_embeddings @ doc_embeddings.T
    print("scores.shape", scores.shape)
    print(scores)
    
    top_indx = int(np.argmax(scores[0]))
    
    print("Document: ", documents[top_indx])
    break
    

Query:  I need help with my password.
query_embeddings.shape  (1, 384)
doc_embeddings.shape  (5, 384)
doc_embeddings.T.shape  (384, 5)
scores.shape (1, 5)
[[-0.03767497 -0.02204201  0.6217671   0.00068602  0.13471472]]
Document:  Customer support helped me reset my account password.
